### PR TITLE
feat: add Traditional Chinese Translations (HK) for the customer portal

### PR DESCRIPTION
**Pull request by iamjrock**
Traditional Chinese Translations (HK) for the customer portal.

Note: We are also adding translations for the larger "shared" Elements translations in another pull request shortly.

### CODE REVIEW

**Comment by pheekus** [comment]
Hey @iamjrock, thanks for contributing :) Once v1.14.0 is out, we are going to release your changes on the beta channel and wait for the `shared` file you're working on to include the complete set of language strings in v1.15.0. One thing though – are you sure you'd like to use `en-hk` code instead of `zh-hk`? Just checking.

**Comment by iamjrock** [comment]
Sorry, my bad - it should be zh-hk!  Thx for spotting that!

________________________________

**Comment by iamjrock** [comment]
One question pls @pheekus : Assuming that I can submit a Pull Request with the remaining shared translations to you in the next 1-2 weeks, when would you hope to release v1.15.0?  Just trying to manage expectations on my side as to when they'll have a Chinese customer portal.....

**Comment by pheekus** [comment]
@iamjrock we've just started working on a complex Elements feature so it might take a while, but it's absolutely no issue for us to move it to v1.16.0 and release v1.15.0 with just the translations.

**Comment by iamjrock** [comment]
ok great, that's really helpful, thx!
________________________________

**Review by pheekus — APPROVED** [review]

**Pull request merged**
